#!/usr/bin/env node
/* Writes the two files a project imports so its tooling knows the design
 * system's roles, both generated from the tokens build.mjs reads:
 *
 *   node .claude/skills/claude-design/scripts/generate.mjs <path/to/design-system.config.mjs>
 *
 * - The safelist (`generated.safelist`, default design-system/safelist.generated.css):
 *   an `@source inline(…)` line per family of the class vocabulary the design
 *   system promises a design. Tailwind emits only classes it finds in source, so
 *   the feed stylesheet imports this file to ship the classes no screen uses yet.
 * - The class-merge registration (`generated.classMerge`, default
 *   src/lib/design-tokens.generated.ts): the role names per tailwind-merge class
 *   group. tailwind-merge has no access to the theme and files a word it does not
 *   know (`rounded-panel`, `font-emphasis`, `type-body`) in a group of its own, so
 *   `cn("rounded-panel", "rounded-pill")` keeps both and CSS order picks the
 *   winner. The project's `cn()` passes `designClassGroups` to
 *   `extendTailwindMerge`.
 *
 * build.mjs runs this first. The token checker regenerates both in memory and
 * fails when a file on disk differs, or when nothing imports it. */

import fs from 'node:fs'
import path from 'node:path'
import { pathToFileURL } from 'node:url'
import { loadConfig } from './config.mjs'
import { buildModel, promisedClasses, SPACING_UTILITIES } from './model.mjs'

const HEADER = (what) =>
  `Generated by .claude/skills/claude-design/scripts/generate.mjs from the design system's tokens — do not edit.\n   ${what}\n   npm run build:design-system rewrites it; the design-token check fails while it is out of date.`

/** One brace group: `{a,b}`, or the bare item when there is only one. */
const braces = (items) => (items.length === 1 ? items[0] : `{${items.join(',')}}`)

export function safelistCss(model, CONFIG) {
  const promised = new Set(promisedClasses(model, CONFIG))
  const lines = []
  const steps = CONFIG.spacing.steps.map(String)
  if (steps.length) lines.push(`${braces(SPACING_UTILITIES)}-${braces(steps)}`)
  const colours = model.colorTokens.map((t) => t.name)
  if (colours.length) lines.push(`{bg,text,border}-${braces(colours)}`)
  const radii = model.radius.map((t) => t.name.replace(model.families.radius, ''))
  if (radii.length) lines.push(`rounded-${braces(radii)}`)
  const types = model.groups.flatMap((g) => g.styles.map((s) => s.name))
  if (types.length) lines.push(`${model.typePrefix}${braces(types)}`)
  // Every promised class is in exactly one of the lines above.
  const covered = promised.size
  return `/* ${HEADER(`Every class the design system's README promises a design: ${covered} classes.`)} */\n${lines.map((l) => `@source inline("${l}");`).join('\n')}\n`
}

/** tailwind-merge's group ids for the corner and spacing utilities. The same ids
 * in v2 and v3. */
const CORNER_GROUPS = ['s', 'e', 't', 'r', 'b', 'l', 'ss', 'se', 'ee', 'es', 'tl', 'tr', 'br', 'bl'].map((c) => `rounded-${c}`)
const SPACING_GROUPS = [
  'p', 'px', 'py', 'ps', 'pe', 'pt', 'pr', 'pb', 'pl',
  'm', 'mx', 'my', 'ms', 'me', 'mt', 'mr', 'mb', 'ml',
  'gap', 'gap-x', 'gap-y', 'size', 'w', 'h', 'min-w', 'min-h', 'max-w', 'max-h',
  'inset', 'inset-x', 'inset-y', 'top', 'right', 'bottom', 'left',
]

/** The id of the group every type role joins — not one of tailwind-merge's own. */
export const TYPE_ROLE_GROUP = 'design-type-role'

export function classMergeTs(model) {
  const radii = model.radius.map((t) => t.name.replace(model.families.radius, ''))
  const shadows = model.shadow.map((t) => t.name.replace(model.families.shadow, ''))
  const types = model.groups.flatMap((g) => g.styles.map((s) => s.name))
  const typeKey = model.typePrefix.replace(/-$/, '')
  const list = (xs) => `[${xs.map((x) => JSON.stringify(x)).join(', ')}]`
  const groups = []
  if (radii.length) {
    groups.push(`  rounded: [{ rounded: RADII }],`)
    for (const g of CORNER_GROUPS) groups.push(`  ${JSON.stringify(g)}: [{ ${JSON.stringify(g)}: RADII }],`)
  }
  if (model.weights.length) groups.push(`  'font-weight': [{ font: WEIGHTS }],`)
  if (shadows.length) groups.push(`  shadow: [{ shadow: SHADOWS }],`)
  if (model.spacingAliases.length) for (const g of SPACING_GROUPS) groups.push(`  ${JSON.stringify(g)}: [{ ${JSON.stringify(g)}: SPACING }],`)
  if (types.length) groups.push(`  ${JSON.stringify(TYPE_ROLE_GROUP)}: [{ ${JSON.stringify(typeKey)}: TYPE_ROLES }],`)
  return `/* ${HEADER('The design system\'s role names per tailwind-merge class group, for `extendTailwindMerge<DesignClassGroupId>({ extend: { classGroups: designClassGroups } })`.')} */

const RADII = ${list(radii)}
const WEIGHTS = ${list(model.weights)}
const SHADOWS = ${list(shadows)}
const SPACING = ${list(model.spacingAliases)}
const TYPE_ROLES = ${list(types)}

export type DesignClassGroupId = ${JSON.stringify(TYPE_ROLE_GROUP)}

export const designClassGroups = {
${groups.join('\n')}
}
`
}

/** The generated files as `[{ rel, file, content }]`, `rel` from the UI package. */
export function generatedFiles(ctx, model) {
  const { CONFIG, PKG } = ctx
  return [
    { rel: CONFIG.generated.safelist, content: safelistCss(model, CONFIG) },
    { rel: CONFIG.generated.classMerge, content: classMergeTs(model) },
  ].map((f) => ({ ...f, file: path.join(PKG, f.rel) }))
}

/** Write them; returns the ones whose content changed. */
export function writeGenerated(ctx, model) {
  const changed = []
  for (const f of generatedFiles(ctx, model)) {
    const before = fs.existsSync(f.file) ? fs.readFileSync(f.file, 'utf8').replace(/\r\n/g, '\n') : null
    if (before === f.content) continue
    fs.mkdirSync(path.dirname(f.file), { recursive: true })
    fs.writeFileSync(f.file, f.content)
    changed.push(f.rel)
  }
  return changed
}

if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  const ctx = await loadConfig(process.argv[2], { tool: 'generate.mjs' })
  const model = buildModel(ctx)
  if (model.problems.length) {
    console.error(`generate: ${model.problems.length} problem(s) — nothing written.\n`)
    for (const p of model.problems) console.error(`  ✗ ${p}`)
    process.exit(1)
  }
  const changed = writeGenerated(ctx, model)
  const files = generatedFiles(ctx, model).map((f) => `${ctx.CONFIG.package}/${f.rel}`)
  console.log(`generate: ${files.join(', ')} — ${changed.length ? `${changed.length} rewritten` : 'already current'}`)
}
